import 'controller/client_s_review_write_a_review_controller.dart';import 'package:flutter/material.dart';import 'package:raj_s_application5/core/app_export.dart';import 'package:raj_s_application5/widgets/custom_button.dart';import 'package:raj_s_application5/widgets/custom_icon_button.dart';import 'package:raj_s_application5/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class ClientSReviewWriteAReviewBottomsheet extends StatelessWidget {ClientSReviewWriteAReviewBottomsheet(this.controller);

ClientSReviewWriteAReviewController controller;

@override Widget build(BuildContext context) { return SingleChildScrollView(child: Container(width: double.maxFinite, child: Container(width: double.maxFinite, padding: getPadding(left: 16, top: 14, right: 16, bottom: 14), decoration: AppDecoration.background.copyWith(borderRadius: BorderRadiusStyle.customBorderTL34), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [SizedBox(width: getHorizontalSize(60), child: Divider(thickness: getVerticalSize(6), color: ColorConstant.gray500)), Padding(padding: getPadding(top: 18), child: Text("msg_what_is_you_rate".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMetropolisSemiBold18)), Padding(padding: getPadding(left: 34, top: 18, right: 33), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(svgPath: ImageConstant.imgStarGray500, height: getSize(36), width: getSize(36), margin: getMargin(bottom: 1)), CustomImageView(svgPath: ImageConstant.imgStarGray500, height: getSize(36), width: getSize(36), margin: getMargin(left: 24, bottom: 1)), CustomImageView(svgPath: ImageConstant.imgStarGray500, height: getSize(36), width: getSize(36), margin: getMargin(left: 24, top: 1)), CustomImageView(svgPath: ImageConstant.imgStarGray500, height: getSize(36), width: getSize(36), margin: getMargin(left: 24, bottom: 1)), CustomImageView(svgPath: ImageConstant.imgStarGray500, height: getSize(36), width: getSize(36), margin: getMargin(left: 24, bottom: 1))])), Container(width: getHorizontalSize(227), margin: getMargin(top: 32), child: Text("msg_please_share_your".tr, maxLines: null, textAlign: TextAlign.center, style: AppStyle.txtMetropolisSemiBold18Gray900)), CustomTextFormField(focusNode: FocusNode(), controller: controller.inactivetextfieldreviewController, hintText: "lbl_your_review".tr, margin: getMargin(top: 17), padding: TextFormFieldPadding.PaddingAll15, fontStyle: TextFormFieldFontStyle.MetropolisRegular14, textInputAction: TextInputAction.done, maxLines: 10), Align(alignment: Alignment.centerLeft, child: Container(margin: getMargin(top: 39), padding: getPadding(left: 6, top: 15, right: 6, bottom: 15), decoration: AppDecoration.outlineBlack90028.copyWith(borderRadius: BorderRadiusStyle.roundedBorder4), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.start, children: [CustomIconButton(height: 52, width: 52, variant: IconButtonVariant.FillRed700, shape: IconButtonShape.CircleBorder26, padding: IconButtonPadding.PaddingAll14, onTap: () {onTapBtnCamera();}, child: CustomImageView(svgPath: ImageConstant.imgCamera)), Padding(padding: getPadding(top: 10), child: Text("lbl_add_your_photos".tr, overflow: TextOverflow.ellipsis, textAlign: TextAlign.left, style: AppStyle.txtMetropolisSemiBold11Gray900))]))), CustomButton(height: getVerticalSize(48), text: "lbl_send_review".tr, margin: getMargin(top: 44, bottom: 30), padding: ButtonPadding.PaddingAll16)])))); } 
onTapBtnCamera() async  { await PermissionManager.askForPermission(Permission.camera);await PermissionManager.askForPermission(Permission.storage);List<String?>? imageList = [];await FileManager().showModelSheetForImage(getImages: (value) async {imageList = value;}); } 
 }
